const chineseZodiac = [
    {
        id: 1,
        name: "Rat",
        years: [2020, 2008, 1996, 1984],
        luckyNumbers: [2, 3],
        luckRating: 7,
        careerRating: 8,
        wealthRating: 6,
        romanceRating: 9,
        healthRating: 7,
    },
    {
        id: 2,
        name: "Ox",
        years: [2021, 2009, 1997, 1985],
        luckyNumbers: [1, 4],
        luckRating: 8,
        careerRating: 9,
        wealthRating: 7,
        romanceRating: 6,
        healthRating: 8,
    },
    {
        id: 3,
        name: "Tiger",
        years: [2022, 2010, 1998, 1986],
        luckyNumbers: [1, 3, 4],
        luckRating: 9,
        careerRating: 7,
        wealthRating: 8,
        romanceRating: 7,
        healthRating: 9,
    },
    {
        id: 4,
        name: "Rabbit",
        years: [2023, 2011, 1999, 1987],
        luckyNumbers: [3, 4, 6],
        luckRating: 6,
        careerRating: 8,
        wealthRating: 9,
        romanceRating: 8,
        healthRating: 7,
    },
    {
        id: 5,
        name: "Dragon",
        years: [2024, 2012, 2000, 1988],
        luckyNumbers: [1, 6, 7],
        luckRating: 8,
        careerRating: 6,
        wealthRating: 7,
        romanceRating: 9,
        healthRating: 8,
    },
    {
        id: 6,
        name: "Snake",
        years: [2025, 2013, 2001, 1989],
        luckyNumbers: [2, 8, 9],
        luckRating: 7,
        careerRating: 9,
        wealthRating: 8,
        romanceRating: 6,
        healthRating: 7,
    },
    {
        id: 7,
        name: "Horse",
        years: [2026, 2014, 2002, 1990],
        luckyNumbers: [2, 3, 7],
        luckRating: 8,
        careerRating: 7,
        wealthRating: 9,
        romanceRating: 8,
        healthRating: 6,
    },
    {
        id: 8,
        name: "Goat",
        years: [2027, 2015, 2003, 1991],
        luckyNumbers: [2, 7],
        luckRating: 9,
        careerRating: 8,
        wealthRating: 6,
        romanceRating: 7,
        healthRating: 8,
    },
    {
        id: 9,
        name: "Monkey",
        years: [2028, 2016, 2004, 1992],
        luckyNumbers: [4, 9],
        luckRating: 6,
        careerRating: 9,
        wealthRating: 7,
        romanceRating: 8,
        healthRating: 9,
    },
    {
        id: 10,
        name: "Rooster",
        years: [2029, 2017, 2005, 1993],
        luckyNumbers: [5, 7, 8],
        luckRating: 8,
        careerRating: 6,
        wealthRating: 9,
        romanceRating: 7,
        healthRating: 8,
    },
    {
        id: 11,
        name: "Dog",
        years: [2030, 2018, 2006, 1994],
        luckyNumbers: [3, 4, 9],
        luckRating: 7,
        careerRating: 8,
        wealthRating: 6,
        romanceRating: 9,
        healthRating: 7,
    },
    {
        id: 12,
        name: "Pig",
        years: [2031, 2019, 2007, 1995],
        luckyNumbers: [2, 5, 8],
        luckRating: 8,
        careerRating: 9,
        wealthRating: 7,
        romanceRating: 6,
        healthRating: 8,
    },
];

export default chineseZodiac;
